name: Build iOS Simulator

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2.24.0
        with:
          flutter-version: '3.22.0'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS Simulator
        run: flutter build ios --simulator --no-codesign

      - name: Check build output
        run: ls build/ios/iphonesimulator

      - name: Zip app
        run: |
          cd build/ios/iphonesimulator
          zip -r Runner.app.zip Runner.app
          mv Runner.app.zip $GITHUB_WORKSPACE/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-simulator-app
          path: Runner.app.zip
