name: Build iOS Simulator

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0' # ou a versão que você usa

      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS Simulator
        run: flutter build ios --simulator --no-codesign

      - name: Zip app
        run: zip -r Runner.app.zip build/ios/iphonesimulator/Runner.app

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ios-simulator-app
          path: Runner.app.zip
