name: Build iOS Simulator

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-15

    steps:
      # 1️⃣ Clona o código
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Instala a versão correta do Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.14.0'  # Atualizado para Dart 3.5

      # 3️⃣ Instala dependências
      - name: Install dependencies
        run: flutter pub get

      # 4️⃣ Build para iOS Simulator
      - name: Build iOS Simulator
        run: flutter build ios --simulator --no-codesign

      # 5️⃣ Debug do output
      - name: Check build output
        run: ls build/ios/iphonesimulator

      # 6️⃣ Cria o .app.zip
      - name: Zip app
        run: |
          cd build/ios/iphonesimulator
          zip -r Runner.app.zip Runner.app
          mv Runner.app.zip $GITHUB_WORKSPACE/

      # 7️⃣ Sobe o .app.zip como artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-simulator-app
          path: Runner.app.zip
